name: Black Formatter

on:
  push:
    paths:
      - 'Backend-Server/**.py'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run Black Formatter
      run: |
        black Backend-Server/**/*.py

    - name: Check for formatting differences
      id: diff
      run: |
        git diff --exit-code || echo "black::changes" >> $GITHUB_ENV

    - name: Commit and push changes
      if: env.black == 'changes'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Apply black formatting"
        git push
