name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Navigate into the Frontend-Client directory
        run: cd Frontend-Client

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: |
          cd ..  # Move back to the main directory
          cd Frontend-Client  # Re-enter the Frontend-Client directory
          npm run build
          npm test
